### ISSUE TITLE
Add that latest version is supported only on fedora32 and centos 8.2

### ISSUE THREAD

**Issue by adwait-thattey** [nmstate/nmstate.github.io#36]
I think it will be helpful to add in the documentation that version 0.2 (and master branch) are supported only in fedora 32 and centos 8.2 onwards and that the previous versions should use version 0.1

I was trying to install and it took me a while to figure this out.

I can add this if it's okay to do so.

**Comment by tyll** [comment]
Thank you, please go ahead.

**Comment by adwait-thattey** [comment]
Should this be enough?

**Comment by tyll** [comment]
@cathay4t it seems that you disagreed with this in the PR, so would you like to close this issue?
