### ISSUE TITLE
Document vlan filtering feature

### ISSUE THREAD

**Issue by maiqueb** [nmstate/nmstate.github.io#39]
Information on how to configure vlan filtering on linux bridges is missing from the docs.

Examples on how to configure it for the most common use cases should be added, e.g. :
  - configure trunk port
  - configure access port 
  - configure trunk port w/ native vlan
  - remove vlan config

**Comment by maiqueb** [comment]
I volunteer to work on this (I had promised before ...).

Have some doubts as to where to add that information ... Adding a sub-section In the linux bridge section ?..

Any opinion @EdDev / @cathay4t / @tyll / @ffmancera  ?

**Comment by ffmancera** [comment]
I would probably add the options under the linux bridge subtree following the pattern of the other interfaces.

**Comment by cathay4t** [comment]
@maiqueb You may try add doc into https://github.com/nmstate/nmstate.github.io/blob/master/devel/api.md
